# Generated by Django 4.0.4 on 2022-05-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.PositiveIntegerField(max_length=16),
        ),
    ]
