# Generated by Django 4.0.4 on 2022-05-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0002_alter_item_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.PositiveIntegerField(),
        ),
    ]
