# Generated by Django 4.0.4 on 2022-05-10 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0003_itemcategory_remove_item_item_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='firesale.itemcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='category_name',
            field=models.CharField(blank=True, default='Óskilgreint', max_length=255),
        ),
    ]
