# Generated by Django 4.0.4 on 2022-05-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0005_alter_itemcategory_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.PositiveIntegerField(max_length=9),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
    ]
