# Generated by Django 4.0.4 on 2022-05-12 18:32

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='country',
            field=django_countries.fields.CountryField(default='Iceland', max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.BigIntegerField(),
        ),
    ]
