# Generated by Django 4.0.4 on 2022-05-12 08:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0005_alter_itemcategory_category_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_alter_payment_name_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='buyer_item', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='firesale.item')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='seller_item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
