# Generated by Django 4.0.4 on 2022-05-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_contactinfo_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='street_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvc',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_month',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_year',
            field=models.PositiveIntegerField(),
        ),
    ]
