# Generated by Django 4.0.4 on 2022-05-12 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0005_alter_itemcategory_category_name'),
        ('payment', '0003_orderinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='firesale.item'),
        ),
    ]
