# Generated by Django 4.0.4 on 2022-05-12 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_card_number_alter_payment_cvc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1111111111111111), django.core.validators.MaxValueValidator(9999999999999999)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvc',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(111), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_month',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
