# Generated by Django 4.0.4 on 2022-05-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_payment_card_number_alter_payment_cvc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_year',
            field=models.IntegerField(),
        ),
    ]
