# Generated by Django 4.0.4 on 2022-05-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_rating',
            field=models.IntegerField(null=True),
        ),
    ]
