# Generated by Django 4.0.4 on 2022-05-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_profile_bio_profile_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
