# Generated by Django 4.0.4 on 2022-05-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
