# Generated by Django 4.0.4 on 2022-05-12 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firesale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.PositiveIntegerField(max_length=9)),
                ('bid_status', models.BooleanField(default=False)),
                ('bid_paid', models.BooleanField(default=False)),
                ('bid_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firesale.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
