# Generated by Django 4.0.4 on 2022-05-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0002_alter_bid_bid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.BigIntegerField(),
        ),
    ]
