# Generated by Django 4.0.4 on 2022-05-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0003_alter_bid_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_status',
        ),
    ]
