# Generated by Django 4.0.4 on 2022-05-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0004_remove_bid_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_status',
            field=models.BooleanField(default=False),
        ),
    ]
