# Generated by Django 4.0.4 on 2022-05-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0005_bid_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_paid',
            field=models.BooleanField(default=False),
        ),
    ]
