# Generated by Django 4.0.4 on 2022-05-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0006_bid_bid_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.PositiveIntegerField(max_length=9),
        ),
    ]
